### PR TITLE
Implemented DELETE

### PR DESCRIPTION
**Pull request by tahmidefaz**

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Comment by lphiri** [comment]
@kruai @tahmidefaz I was under the impression that tags are not deletable once added. Whats the usecase for this requirement?

**Comment by kruai** [comment]
@lphiri We assumed we'd want full CRUD. If this isn't the case, please let us know and we can close this ticket.

**Comment by shdunning** [comment]
@lphiri I'll check with Product, but it seems we would actually want this API call to satisfy a missing use case of "tags that are no longer associated with hosts should be purged from the taxonomy service". @iphands mentioned a while back that if a new tag payload comes in for a known host then we should overwrite any associated tags at that namespace. This would allow for "stale tags" in the taxonomy service if we don't somehow delete them. 

I've posted some questions in that IPP

**Comment by iphands** [comment]
> @lphiri I'll check with Product, but it seems we would actually want this API call to satisfy a missing use case of "tags that are no longer associated with hosts should be purged from the taxonomy service".

I too thought they would required to be immutable for historical reporting purposes.
Check with Jag or the IPP for more info there though 

> @iphands mentioned a while back that if a new tag payload comes in for a known host then we should overwrite any associated tags at that namespace. This would allow for "stale tags" in the taxonomy service if we don't somehow delete them.

Shaun I think this covers the Inventory side well, but not the taxonomy service.

Can we just close this for now and revisit once we have a solid use case for DELETE?

**Comment by tahmidefaz** [comment]
Closing, as per the conversation above :no_entry_sign:

**Pull request closed without merging**
